/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;

import java.util.Optional;

import static org.junit.Assert.*;

public class UserStoreTest {

    private UserStore store;

    @Before
    public void setUp() throws Exception {
        store = new UserStore();
    }

    @Test public void itHoldsOneUser() {
        Address address = new Address("805 Red Bridge Rd.", "600747");
        User user = new User("Eric", "Smith", address);

        store.add(user);

        Optional<User> foundUser = store.firstByFirstName("Eric");
        assertTrue("User is not present", foundUser.isPresent());
    }

    @Test
    public void itReturnsNothingWhenNoUserIsFoundByThatName() {
        Optional<User> foundUser = store.firstByFirstName("Eric");

        assertFalse("User was found that should not exist", foundUser.isPresent());
    }
}
